export const homePage = '/'
export const loginPage = '/login'
export const signUpPage = '/signUp'
export const resetPassword = '/reset'
export const startGamePage = '/leaderBoard'
export const gamePage = '/games'