export const loginTitle = 'login'
export const singupTitle = 'signup'
export const Slide = 'Slide'
export const aboutTitle = 'about'
export const rulesTitle = 'rules'
export const webName = 'PlayOut'
export const mainTitle = 'Welcome To PlayOut'