export const boardLength = 122
export const winCondition = 0
export const invadersIntervalTime = 1200
export const shotIntervalTime = 10
export const invadersLength = 34
export const startPlace = { tank: 116, shot: 0 }
export const finalPlace = 109
export const nextPlace = 11
export const firstPlace = 11
export const arrowKey = { right: 'ArrowRight', left: 'ArrowLeft', space:' ' }
export const keyDown = 'keydown'
export const limit = { left: 111, right: 121 }
export const gameTitle = 'space invaders'